######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 27 22:25:35 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello_qt.cpp

INCLUDEPATH += /usr/include/poppler/qt4
INCLUDEPATH += /usr/include/opencv

LIBS +=-lpoppler-qt4
LIBS +=`pkg-config --libs opencv`


